export let PaisesOriginalEquipos = {
  "sm_state_GB": { "nombre": "Reino Unido" , "color": "#FF5733"},
  "sm_state_SE": { "nombre": "Suecia" , "color": "#33FF57"},
  "sm_state_UA": { "nombre": "Ucrania" , "color": "#3366FF"},
  "sm_state_SI": { "nombre": "Eslovenia" , "color": "#A93226"},
  "sm_state_SK": { "nombre": "Eslovaquia" , "color": "#FFCE63"},
  "sm_state_MK": { "nombre": "Macedonia" , "color": "#0B3C49"},
  "sm_state_CY": { "nombre": "Chipre" , "color": "#982136"},
  "sm_state_RS": { "nombre": "Serbia" , "color": "#77D970"},
  "sm_state_MD": { "nombre": "Moldavia" , "color": "#6E45E2"},
  "sm_state_ME": { "nombre": "Montenegro" , "color": "#FF7F00"},
  "sm_state_ES": { "nombre": "España" , "color": "#1A936F"},
  "sm_state_IE": { "nombre": "Irlanda" , "color": "#DDA15E"},
  "sm_state_AT": { "nombre": "Austria" , "color": "#865680"},
  "sm_state_CZ": { "nombre": "República Checa" , "color": "#F4C542"},
  "sm_state_IT": { "nombre": "Italia" , "color": "#00818A"},
  "sm_state_AL": { "nombre": "Albania" , "color": "#D44919"},
  "sm_state_IS": { "nombre": "Islandia" , "color": "#5B8B2A"},
  "sm_state_EE": { "nombre": "Estonia" , "color": "#007991"},
  "sm_state_AD": { "nombre": "Andorra" , "color": "#EA5C5A"},
  "sm_state_CH": { "nombre": "Suiza" , "color": "#FFC512"},
  "sm_state_XK": { "nombre": "Kosovo" , "color": "#3C53A3"},
  "sm_state_PL": { "nombre": "Polonia" , "color": "#8E44AD"},
  "sm_state_RO": { "nombre": "Rumania" , "color": "#3498DB"},
  "sm_state_LU": { "nombre": "Luxemburgo" , "color": "#28B463"},
  "sm_state_LT": { "nombre": "Lituania" , "color": "#E77F67"},
  "sm_state_LV": { "nombre": "Letonia" , "color": "#59ABE3"},
  "sm_state_TR": { "nombre": "Turquía" , "color": "#F39C12"},
  "sm_state_NO": { "nombre": "Noruega" , "color": "#27AE60"},
  "sm_state_PT": { "nombre": "Portugal" , "color": "#E74C3C"},
  "sm_state_NL": { "nombre": "Países Bajos" , "color": "#3498DB"},
  "sm_state_GR": { "nombre": "Grecia" , "color": "#28B463"},
  "sm_state_BY": { "nombre": "Bielorrusia" , "color": "#D35400"},
  "sm_state_FI": { "nombre": "Finlandia" , "color": "#F1C40F"},
  "sm_state_HU": { "nombre": "Hungría" , "color": "#3498DB"},
  "sm_state_BA": { "nombre": "Bosnia" , "color": "#28B463"},
  "sm_state_DE": { "nombre": "Alemania" , "color": "#983228"},
  "sm_state_HR": { "nombre": "Croacia" , "color": "#8E44AD"},
  "sm_state_DK": { "nombre": "Dinamarca" , "color": "#D35400"},
  "sm_state_BG": { "nombre": "Bulgaria" , "color": "#F1C40F"},
  "sm_state_FR": { "nombre": "Francia" , "color": "#3498DB"},
  "sm_state_BE": { "nombre": "Bélgica" , "color": "#28B463"}
}


export let PaisesFronterasOriginales = {
  "sm_state_GB": ["sm_state_IE", "sm_state_FR", "sm_state_IS"],
  "sm_state_SE": ["sm_state_NO", "sm_state_FI", "sm_state_DK"],
  "sm_state_UA": ["sm_state_PL", "sm_state_SK", "sm_state_HU", "sm_state_RO", "sm_state_MD", "sm_state_BY"],
  "sm_state_SI": ["sm_state_AT", "sm_state_IT", "sm_state_HR", "sm_state_HU"],
  "sm_state_SK": ["sm_state_CZ", "sm_state_AT", "sm_state_HU", "sm_state_PL", "sm_state_UA"],
  "sm_state_MK": ["sm_state_GR", "sm_state_BG", "sm_state_RS", "sm_state_AL", "sm_state_XK"],
  "sm_state_CY": ["sm_state_TR"],
  "sm_state_RS": ["sm_state_HU", "sm_state_RO", "sm_state_BG", "sm_state_MK", "sm_state_HR", "sm_state_BA", "sm_state_ME"],
  "sm_state_MD": ["sm_state_UA", "sm_state_RO"],
  "sm_state_ME": ["sm_state_HR", "sm_state_BA", "sm_state_RS", "sm_state_AL"],
  "sm_state_ES": ["sm_state_PT", "sm_state_FR", "sm_state_AD"],
  "sm_state_IE": ["sm_state_GB", "sm_state_IS"],
  "sm_state_AT": ["sm_state_DE", "sm_state_CZ", "sm_state_SK", "sm_state_HU", "sm_state_SI", "sm_state_IT", "sm_state_CH"],
  "sm_state_CZ": ["sm_state_DE", "sm_state_AT", "sm_state_SK", "sm_state_PL"],
  "sm_state_IT": ["sm_state_FR", "sm_state_CH", "sm_state_SI", "sm_state_AT"],
  "sm_state_AL": ["sm_state_ME", "sm_state_XK", "sm_state_MK", "sm_state_GR"],
  "sm_state_GR": ["sm_state_MK", "sm_state_AL", "sm_state_TR", "sm_state_BG"],
  "sm_state_BY": ["sm_state_LV", "sm_state_LT", "sm_state_PL", "sm_state_UA"],
  "sm_state_FI": ["sm_state_SE", "sm_state_NO"],
  "sm_state_HU": ["sm_state_AT", "sm_state_SK", "sm_state_RS", "sm_state_HR", "sm_state_SI", "sm_state_UA"],
  "sm_state_BA": ["sm_state_HR", "sm_state_RS", "sm_state_ME", "sm_state_TR"],
  "sm_state_DE": ["sm_state_AT", "sm_state_CZ", "sm_state_DK", "sm_state_BE", "sm_state_NL", "sm_state_LU"],
  "sm_state_HR": ["sm_state_SI", "sm_state_HU", "sm_state_RS", "sm_state_BA", "sm_state_ME", "sm_state_TR"],
  "sm_state_DK": ["sm_state_DE", "sm_state_SE"],
  "sm_state_BG": ["sm_state_TR", "sm_state_GR", "sm_state_MK", "sm_state_RS", "sm_state_RO", "sm_state_RS"],
  "sm_state_FR": ["sm_state_GB", "sm_state_ES", "sm_state_IT", "sm_state_CH", "sm_state_BE", "sm_state_LU"],
  "sm_state_BE": ["sm_state_NL", "sm_state_DE", "sm_state_LU", "sm_state_FR"],
  "sm_state_NL": ["sm_state_BE", "sm_state_DE"],
  "sm_state_LU": ["sm_state_BE", "sm_state_FR", "sm_state_DE"],
  "sm_state_PT": ["sm_state_ES"],
  "sm_state_LT": ["sm_state_LV", "sm_state_BY", "sm_state_PL"],
  "sm_state_LV": ["sm_state_EE", "sm_state_LT", "sm_state_BY"],
  "sm_state_TR": ["sm_state_GR", "sm_state_BG", "sm_state_BA", "sm_state_HR", "sm_state_CY"],
  "sm_state_NO": ["sm_state_SE", "sm_state_FI", "sm_state_IS"],
  "sm_state_PT": ["sm_state_ES"],
  "sm_state_AD": ['sm_state_ES'],
  "sm_state_CH": ['sm_state_AT', 'sm_state_IT', 'sm_state_FR'],
  "sm_state_EE": ['sm_state_LV'],
  "sm_state_IS": ["sm_state_NO", "sm_state_IE", "sm_state_GB"],
  "sm_state_PL": ['sm_state_UA', 'sm_state_SK', 'sm_state_CZ', 'sm_state_BY', 'sm_state_LT'],
  "sm_state_RO": ['sm_state_UA', 'sm_state_RS', 'sm_state_MD', 'sm_state_BG'],
  "sm_state_XK": ['sm_state_MK', 'sm_state_AL']
}